// API route serves frequently-changing price data.
// `force-dynamic` ensures no ISR writes are generated by this route — caching
// is delegated to the Vercel CDN via `Cache-Control: s-maxage=60` on the response.
export const dynamic = 'force-dynamic';

const OUNCE = 31.1035;
const MARKUP = 1.02;
const KARATS = { 24: 1, 22: 0.9167, 21: 0.875, 18: 0.75, 14: 0.5833 };

// In-memory fallback to protect bot + visitors from upstream 403s.
let lastGood = null;
const FALLBACK_MAX_AGE_MS = 60 * 60 * 1000; // 1 hour

export async function GET() {
  try {
    const res = await fetch('https://data-asg.goldprice.org/dbXRates/SAR', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        'Accept': 'application/json, text/plain, */*',
        'Origin': 'https://goldprice.org',
        'Referer': 'https://goldprice.org/',
      },
      // Share upstream fetch across edge invocations within 60s window.
      next: { revalidate: 60 },
    });

    if (!res.ok) throw new Error(`goldprice.org: ${res.status}`);

    const data = await res.json();
    const item = data?.items?.[0];
    if (!item?.xauPrice) throw new Error('Invalid data');

    const sarPerOunce = item.xauPrice;
    const usdPerOunce = sarPerOunce / 3.75;
    const gram24 = (sarPerOunce / OUNCE) * MARKUP;

    const prices = {};
    for (const [k, purity] of Object.entries(KARATS)) {
      prices[k] = {
        gram: +(gram24 * purity).toFixed(2),
        ounce: +(gram24 * purity * OUNCE).toFixed(2),
        kilo: +(gram24 * purity * 1000).toFixed(2),
      };
    }

    const payload = {
      success: true,
      // Bot reads rates.SAR and rates.USD — do not rename.
      rates: {
        SAR: sarPerOunce,
        USD: +usdPerOunce.toFixed(2),
      },
      prices,
      // Bot reads change_percent and change_value — do not rename.
      change_percent: item.pcXau || 0,
      change_value: item.chgXau || 0,
      updatedAt: new Date().toISOString(),
      source: 'goldprice.org',
    };

    lastGood = { payload, timestamp: Date.now() };

    return Response.json(payload, {
      headers: { 'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300' },
    });
  } catch (error) {
    console.error('Prices API error:', error);

    // Serve last good value to protect bot tweets and live updaters.
    if (lastGood && Date.now() - lastGood.timestamp < FALLBACK_MAX_AGE_MS) {
      return Response.json(
        { ...lastGood.payload, source: 'goldprice.org (stale)', stale: true },
        { headers: { 'Cache-Control': 'public, s-maxage=30, stale-while-revalidate=60' } }
      );
    }

    return Response.json(
      { success: false, error: error.message },
      { status: 500, headers: { 'Cache-Control': 'public, s-maxage=30' } }
    );
  }
}
