// API route serves frequently-changing price data.
// `force-dynamic` ensures no ISR writes are generated by this route — caching
// is delegated to the Vercel CDN via the `Cache-Control: s-maxage=60` header
// on the response. The combination gives us:
//   - 0 ISR writes
//   - ~1 function invocation per 60s of traffic (CDN absorbs the rest)
//   - In-memory fallback for upstream 403s within a warm Lambda
export const dynamic = 'force-dynamic';

const OUNCE = 31.1035;
const MARKUP = 1.02;
const KARATS = {
  24: 1,
  22: 0.9167,
  21: 0.875,
  18: 0.75,
  14: 0.5833,
};

// In-memory fallback for the last successful response.
// Survives within a single warm Lambda; protects against goldprice.org 403s.
let lastGood = null; // { payload, timestamp }
const FALLBACK_MAX_AGE_MS = 60 * 60 * 1000; // 1 hour

export async function GET() {
  try {
    // Headers identical to /api/prices (proven working against goldprice.org).
    const res = await fetch('https://data-asg.goldprice.org/dbXRates/SAR', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        'Accept': 'application/json, text/plain, */*',
        'Origin': 'https://goldprice.org',
        'Referer': 'https://goldprice.org/',
      },
      // Let Next.js Data Cache hold the upstream value for 60s — multiple
      // simultaneous edge invocations share the same fetch result.
      next: { revalidate: 60 },
    });

    if (!res.ok) throw new Error(`goldprice.org returned ${res.status}`);

    const data = await res.json();
    const item = data?.items?.[0];

    if (!item?.xauPrice) throw new Error('Invalid data from goldprice.org');

    const sarPerOunce = item.xauPrice;
    const gram24 = (sarPerOunce / OUNCE) * MARKUP;

    const prices = {};
    for (const [k, purity] of Object.entries(KARATS)) {
      prices[k] = {
        gram: +(gram24 * purity).toFixed(2),
        ounce: +(gram24 * purity * OUNCE).toFixed(2),
        kilo: +(gram24 * purity * 1000).toFixed(2),
      };
    }

    const silverSarPerOunce = item.xagPrice || 0;

    const payload = {
      success: true,
      prices,
      xauSar: sarPerOunce,
      xagSar: silverSarPerOunce,
      change: {
        amount: item.chgXau || 0,
        percent: item.pcXau || 0,
      },
      updatedAt: new Date().toISOString(),
      source: 'goldprice.org',
    };

    // Store in memory for fallback on next upstream failure.
    lastGood = { payload, timestamp: Date.now() };

    return Response.json(payload, {
      headers: {
        // Vercel edge cache: 60s fresh + 120s stale-while-revalidate.
        // Reduces function invocations by ~95% under bursty traffic.
        'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
      },
    });
  } catch (error) {
    // Upstream failed — serve the last good value if we have one recent enough.
    // Prevents the "every visitor = 500 error = invocation" cascade.
    if (lastGood && Date.now() - lastGood.timestamp < FALLBACK_MAX_AGE_MS) {
      return Response.json(
        { ...lastGood.payload, source: 'goldprice.org (stale)', stale: true },
        {
          headers: {
            // Shorter cache so we retry upstream quickly.
            'Cache-Control': 'public, s-maxage=30, stale-while-revalidate=60',
          },
        }
      );
    }

    // No fallback available — cache the error briefly so we don't hammer
    // the function on persistent upstream failure.
    return Response.json(
      { success: false, error: error.message },
      {
        status: 500,
        headers: {
          'Cache-Control': 'public, s-maxage=30',
        },
      }
    );
  }
}
